import {
  ShoppingCart,
  UtensilsCrossed,
  Bus,
  Home,
  Zap,
  Heart,
  Gamepad2,
  MoreHorizontal,
  Briefcase,
  Laptop,
  Tv,
  Shirt,
  BookOpen,
  Shield,
  Gift,
  Plane,
  Landmark,
  PawPrint,
  TrendingUp,
  HelpCircle,
  Wallet,
  PiggyBank,
  CreditCard,
  Banknote,
  SplitSquareHorizontal,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  ShoppingCart,
  UtensilsCrossed,
  Bus,
  Home,
  Zap,
  Heart,
  Gamepad2,
  MoreHorizontal,
  Briefcase,
  Laptop,
  Tv,
  Shirt,
  BookOpen,
  Shield,
  Gift,
  Plane,
  Landmark,
  PawPrint,
  TrendingUp,
  HelpCircle,
  // Account icons (ACCOUNT_ICONS) — Landmark/TrendingUp already present above.
  Wallet,
  PiggyBank,
  CreditCard,
  Banknote,
  // Split-transaction chip (SPLIT_ICON).
  SplitSquareHorizontal,
};

export function resolveIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? HelpCircle;
}
